---
schema:
  procedures: {}
  tables:
    files:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - version_id
          match_type: ''
          name: files_fk_version_id
          on_delete: CASCADE
          on_update: CASCADE
          options: []
          reference_fields:
            - id
          reference_table: versions
          type: FOREIGN KEY
      fields:
        file:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: file
          order: 4
          size:
            - 0
        filename:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: filename
          order: 3
          size:
            - 255
        id:
          data_type: int
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 1
          size:
            - 0
        version_id:
          data_type: int
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: version_id
          order: 2
          size:
            - 0
      indices:
        - fields:
            - version_id
          name: files_idx_version_id
          options: []
          type: NORMAL
      name: files
      options: []
      order: 6
    projects:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - user_id
          match_type: ''
          name: projects_fk_user_id
          on_delete: CASCADE
          on_update: CASCADE
          options: []
          reference_fields:
            - id
          reference_table: users
          type: FOREIGN KEY
      fields:
        description:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: description
          order: 5
          size:
            - 0
        id:
          data_type: int
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 1
          size:
            - 0
        lc_name:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: lc_name
          order: 4
          size:
            - 255
        name:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: name
          order: 3
          size:
            - 255
        user_id:
          data_type: int
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: user_id
          order: 2
          size:
            - 0
      indices:
        - fields:
            - user_id
          name: projects_idx_user_id
          options: []
          type: NORMAL
      name: projects
      options: []
      order: 3
    roles:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - name
          match_type: ''
          name: roles_name
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: UNIQUE
      fields:
        id:
          data_type: int
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 1
          size:
            - 0
        name:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 1
          name: name
          order: 2
          size:
            - 255
      indices: []
      name: roles
      options: []
      order: 1
    user_roles:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - role_id
            - user_id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - role_id
          match_type: ''
          name: user_roles_fk_role_id
          on_delete: CASCADE
          on_update: CASCADE
          options: []
          reference_fields:
            - id
          reference_table: roles
          type: FOREIGN KEY
        - deferrable: 1
          expression: ''
          fields:
            - user_id
          match_type: ''
          name: user_roles_fk_user_id
          on_delete: CASCADE
          on_update: CASCADE
          options: []
          reference_fields:
            - id
          reference_table: users
          type: FOREIGN KEY
      fields:
        role_id:
          data_type: int
          default_value: ~
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: role_id
          order: 2
          size:
            - 0
        user_id:
          data_type: int
          default_value: ~
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: user_id
          order: 1
          size:
            - 0
      indices:
        - fields:
            - role_id
          name: user_roles_idx_role_id
          options: []
          type: NORMAL
        - fields:
            - user_id
          name: user_roles_idx_user_id
          options: []
          type: NORMAL
      name: user_roles
      options: []
      order: 4
    users:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - email
          match_type: ''
          name: users_email
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: UNIQUE
        - deferrable: 1
          expression: ''
          fields:
            - lc_username
          match_type: ''
          name: users_lc_username
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: UNIQUE
        - deferrable: 1
          expression: ''
          fields:
            - username
          match_type: ''
          name: users_username
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: UNIQUE
      fields:
        email:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 1
          name: email
          order: 4
          size:
            - 255
        id:
          data_type: int
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 1
          size:
            - 0
        lc_username:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 1
          name: lc_username
          order: 3
          size:
            - 255
        password:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: password
          order: 5
          size:
            - 50
        set_password_code:
          data_type: varchar
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: set_password_code
          order: 6
          size:
            - 80
        username:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 1
          name: username
          order: 2
          size:
            - 255
      indices: []
      name: users
      options: []
      order: 2
    versions:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - project_id
            - version
          match_type: ''
          name: versions_project_id_version
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: UNIQUE
        - deferrable: 1
          expression: ''
          fields:
            - project_id
          match_type: ''
          name: versions_fk_project_id
          on_delete: CASCADE
          on_update: CASCADE
          options: []
          reference_fields:
            - id
          reference_table: projects
          type: FOREIGN KEY
      fields:
        description:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: description
          order: 5
          size:
            - 0
        gz_file:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: gz_file
          order: 8
          size:
            - 0
        id:
          data_type: int
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 1
          size:
            - 0
        project_id:
          data_type: int
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 1
          name: project_id
          order: 2
          size:
            - 0
        status:
          data_type: varchar
          default_value: new
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: status
          order: 9
          size:
            - 10
        tar_file:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: tar_file
          order: 6
          size:
            - 0
        timestamp:
          data_type: datetime
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: timestamp
          order: 4
          size:
            - 0
        version:
          data_type: int
          default_value: 1
          is_nullable: 0
          is_primary_key: 0
          is_unique: 1
          name: version
          order: 3
          size:
            - 0
        zip_file:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: zip_file
          order: 7
          size:
            - 0
      indices:
        - fields:
            - project_id
          name: versions_idx_project_id
          options: []
          type: NORMAL
      name: versions
      options: []
      order: 5
  triggers: {}
  views: {}
translator:
  add_drop_table: 0
  filename: ~
  no_comments: 0
  parser_args:
    sources:
      - File
      - Project
      - Role
      - User
      - UserRole
      - Version
  parser_type: SQL::Translator::Parser::DBIx::Class
  producer_args: {}
  producer_type: SQL::Translator::Producer::YAML
  show_warnings: 0
  trace: 0
  version: 0.11021
